version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: "1.29.2"
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start Docker Compose service
          command: |
            COMPOSE_PROFILES=grafana,telegraf docker-compose up -d

            sleep 15

            curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8086/ping
            curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000/api/health