version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     
     - run:
         name: Install Docker Compose
         environment:
           COMPOSE_VERSION: '1.29.2'
         command: |
           curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
           chmod +x ~/docker-compose
           sudo mv ~/docker-compose /usr/local/bin/docker-compose

     - run: |
         COMPOSE_PROFILES=grafana,telegraf docker-compose up -d

     - run: sleep 30

     - run: docker run --network container:influx \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://influx:8086/ping

     - run: docker run --network container:influx \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://grafana:3000/api/health
